### ISSUE TITLE
Consent String Version Support

### ISSUE THREAD

**Issue by raviiitp** [InteractiveAdvertisingBureau/Consent-String-SDK-Java#13]
Hi,

How is the application planning to support different consent string parsers for different versions in the future? Shouldn't the application first parse the version and then use a consent-string parser for that version? Your thoughts?

**Comment by chrispaterson** [comment]
Good question, I'm not sure anyone has been thinking past version 1

**Comment by raviiitp** [comment]
OK. Cool, thanks for your response.

**Comment by lanusau** [comment]
This is implemented in #30
