### ISSUE TITLE
isVendorAllowed hangs on following consent string

### ISSUE THREAD

**Issue by tkyang99** [InteractiveAdvertisingBureau/Consent-String-SDK-Java#14]
BONjw1AONnXIfABABDENAR6AAAAJqAGAAEABUAGoAWQAyAB2

Hangs when I try to call isVendorAllowed with an ID value of 22 or greater.

Seems to get stuck in an infinite loop in findVendorIdInRange().

**Comment by adityar4** [comment]
This is addressed in [PR 11](https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/pull/11).

**Comment by chrispaterson** [comment]
Merged PR 11
