### ISSUE TITLE
Removing consent string construction

### ISSUE THREAD

**Issue by GytisZ** [InteractiveAdvertisingBureau/Consent-String-SDK-Java#25]
While investigating https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/pull/24 I've noticed that the current implementation takes a base64 consent string, decodes / parses it and constructs the `VendorConsent` object. While doing that it takes all the fields and reconstructs the consent string. I wonder what's the function of that part of code?

 It seems to only add complexity and room for error (as per the aforementioned pull request). Furthermore it seems really inefficient to do all that work when base64 string is already available. In high-load adtech environment this is seems way too costly.

If it's meant as some kind of validation / sanity check, then maybe a better solution would be having a separate encode/decode functions, which could be used in tests and users that really want them.

**Comment by lanusau** [comment]
I agree. It seems to me that concerns of representing Consent and encoding/decoding base64 string should be separated. Right now they are mixed together and that causes these issues.
I am also thinking for the high load environment, it would be better to have VendorConsent object backed by byte array only, with methods extracting data from byte array on the fly, without constructing any other fields to store extracted data. Assuming in majority of the cases field needs to be read once this would not cause increase in CPU cycles but would really cut down on garbage generation. 
Not sure how much of this can be done without breaking existing API, but I'll give it a stab once I get few min.

**Comment by lanusau** [comment]
Resolved in #30
