### ISSUE TITLE
unnecessary set created in heavily used API

### ISSUE THREAD

**Issue by hydrogen2** [InteractiveAdvertisingBureau/Consent-String-SDK-Java#33]
https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/blob/f1ee80693394fe219fb62951e6d3de04d7b71c3d/src/main/java/com/iab/gdpr/consent/implementation/v1/ByteBufferBackedVendorConsent.java#L104

isPurposeAllowed() is a heavily used API. Why don't you just directly check the bit, instead of getting all the bits and creating the unnecessary set every time?

**Comment by lanusau** [comment]
Sounds like a good optimization. Can you create a pull request?

**Comment by hydrogen2** [comment]
https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/pull/34 here

**Comment by lanusau** [comment]
Thank you! Merged
