### ISSUE TITLE
java.lang.IllegalArgumentException: Input byte[] should at least have 2 bytes for base64 bytes

### ISSUE THREAD

**Issue by bmwcmw** [InteractiveAdvertisingBureau/Consent-String-SDK-Java#37]
https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/blob/75c6492e56051daa3a5e8271a43ceaad74720d9b/src/main/java/com/iab/gdpr/consent/VendorConsentDecoder.java#L23

Hi,

How can we deal with that if the input contains only one character ? Currently we're always jumping into : 
```
Exception in thread "main" java.lang.IllegalArgumentException: Input byte[] should at least have 2 bytes for base64 bytes
	at java.util.Base64$Decoder.outLength(Base64.java:659)
	at java.util.Base64$Decoder.decode(Base64.java:525)
	at java.util.Base64$Decoder.decode(Base64.java:549)
```

Thanks.

**Comment by lanusau** [comment]
Are you saying there can be a valid consent string with just 1 character?

**Comment by bmwcmw** [comment]
Bidswich is sending 0 or 1 in the user.ext.consent field : 
http://www.bidswitch.com/policies/gdpr/

So it has already made tons of exception log since this exception was not managed in our application.

**Comment by lanusau** [comment]
Values 0 or 1 are not valid values for consent string. It seems that Bidswitch is not sending you the consent string as defined by IAB, instead they are sending boolean value that has to be interpreted by their specifications. This SDK can only be used to interpret GDPR consent string as defined by IAB spec. 

So the exception is expected and valid.

**Comment by bmwcmw** [comment]
You're right, we're going to do differently for bidswitch and mopub which is in the same case.

So it was just the unchecked exception which disturbed me. Since it's intended, I close this issue.
