### ISSUE TITLE
Getting 'ArrayIndexOutOfBoundsException' when calling isVendorAllowed()

### ISSUE THREAD

**Issue by ahmad-najeeb** [InteractiveAdvertisingBureau/Consent-String-SDK-Java#41]
Trying to decode this consent string: 'BOUy_skOUy_skABABBENA8-AAAAbN7'

Max Vendor ID is '435', but when I trying to see if '4' is an allowed vendor ID, I get the following exception: `java.lang.ArrayIndexOutOfBoundsException: 22`

Any ideas what is causing this and what it means ?

**Comment by lanusau** [comment]
This is a corrupt consent string. It uses bitmap encoding with max vendor ID of 435, which means there should be 435 bits after VENDOR_BITFIELD_OFFSET=173, or 608 bits encoded into 76 bytes. However, this string has only 22 bytes. 
We could probably throw a better exception, with a name like InvalidEncoding or something. I will make that change once I have some time.
