### ISSUE TITLE
Is VendorConsent.getAllowedVendorIds missing by intent?

### ISSUE THREAD

**Issue by ssick** [InteractiveAdvertisingBureau/Consent-String-SDK-Java#42]
I noticed that the interface `com.iab.gdpr.consent.VendorConsent` does not specify a method `getAllowedVendorIds`, as opposed to `getAllowedPurposeIds`. Is this intended?

I have a requirement for this method in my implementation where I use `com.conversantmedia.gdpr:consent-string-sdk-java`. Based on the `consent-string` that the user has stored, we need to show them in the UI which of the vendors they have given consent and which they haven't.

Currently I have to work around this by checking `VendorConsent::isVendorAllowed(vendorId)` for all `vendorId`s from `1..maxVendorId`. I'd think there is a much more efficient way to do this by having access to the stored `Bits`.

If it makes sense to have this method added, I'd be happy to try and provide a PR with an implementation.

**Comment by lanusau** [comment]
I don't think this was intended, just that nobody needed it until now. Should be easy to add. PR would be welcome.

**Comment by ssick** [comment]
Thanks @lanusau!

I opened #43 which addresses this issue.

**Comment by ssick** [comment]
Resolved by #43 ✅
