### ISSUE TITLE
Error: Illegal base64 character

### ISSUE THREAD

**Issue by eysegal** [InteractiveAdvertisingBureau/Consent-String-SDK-Java#49]
When passing the following GDPR consent string: 

> BOx/HbgOx/HbgAGABBENDF+AAAAvKAbAAqACAAFQALQAdgBFACSAFIALYAXgAxAB3AEAAIQATIAnABQgDAAGgAOIAgwBCACJgIAgQeBCACQAFhg

I'm getting the following error:
```
java.lang.IllegalArgumentException: Illegal base64 character 2f
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at com.iab.gdpr.consent.VendorConsentDecoder.fromBase64String(VendorConsentDecoder.java:23)
```

The consent string seem to resolve properly on https://acdn.origin.appnexus.net/cmp/docs/#/tools/vendor-cookie-inspector 

Is this a bug?

**Comment by chrispaterson** [comment]
That consent string is not a base64url encoded string.  replace the `+` with `-` and the `/` with `_`

**Comment by eysegal** [comment]
Thanks @chrispaterson
