### ISSUE TITLE
handle defaultConsent properly

### ISSUE THREAD

**Issue by captify-msladkiy** [InteractiveAdvertisingBureau/Consent-String-SDK-Java#5]
There are two potential issues with [current version in github](https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/commit/c2d1f192df13c5d9c98d50369b17abe7f6377d5a])

1. it is either documentation was changed again or the defaultConsent handling is broken. If defaultConsent == 0, the vendor is *not* allowed despite being present in the range. Possible fix to use *^* instead of *&&* [here](https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/blob/master/src/main/java/ConsentStringParser.java#L265)
2. the single entries are not found in ranges

here are tests for addressed issues 
```
@Test
	public void testRangeDefault0() throws ParseException {
		String consentString = "BONRP7YONRP7YAAABAENAACQAAAAqACAAFAAUACA"; // range: [2, (5,8)]

		ConsentStringParser consent = new ConsentStringParser(consentString);

		assertTrue(consent.isVendorAllowed(2));
		assertTrue(consent.isVendorAllowed(6));

		assertFalse(consent.isVendorAllowed(9));
	}


	@Test
	public void testRangeDefault1() throws ParseException {
		String consentString = "BONRP7YONRP7YAAABAENAACQAAAArACAAFAAUACA"; // range: [2, (5,8)]

		ConsentStringParser consent = new ConsentStringParser(consentString);

		assertFalse(consent.isVendorAllowed(2));
		assertFalse(consent.isVendorAllowed(6));

		assertTrue(consent.isVendorAllowed(9));
	}

	@Test
	public void findSingleEntryInRange() throws ParseException {
		String consentString = "BONRP7YONRP7YAAABAENAACQAAAAqABAAEA"; // DefaultConsent: 0, range: [2]

		ConsentStringParser consent = new ConsentStringParser(consentString);

		assertFalse(consent.isVendorAllowed(2));
	}
```

**Comment by chrispaterson** [comment]
Is this resolved by 
https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/commit/81928a53b829217682296ab2ff06243ef12cb142
and
https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java/commit/eb8df16caea32cc0c463d03dffe14a62ed057451

**Comment by captify-msladkiy** [comment]
hi. tnx for Maven btw.
the tests attached in the issue description pass with applied fixes 👌. If assume that encoded consent string was swapped with proper encode for `defaultValue` then old range tests also pass 👌.  
the issue is resolved and could be closed. thanks
