### ISSUE TITLE
Establish and document versioning and release policies

### ISSUE THREAD

**Issue by turu** [InteractiveAdvertisingBureau/Consent-String-SDK-Java#7]
Once the library starts being published to a public Maven repository (see issue #6), some versioning and branching/release strategies should be established, documented and enforced in the repository so that the project can evolve safely, while being used in production by the public.

As far as versioning is concerned, Semantic Versioning (https://semver.org/) is the best choice IMO. 

And when it comes to the branching/release strategy, a simple yet effective one (especially in concert with semantic versioning) is to maintain a master branch holding the newest, working snapshot as well as release branches for every major (or minor) version (ex. release/1.x, release/2.x) When such a branch is updated, artifacts built from a release branch can be safely published to a public Maven repository. This kind of branching policy also facilitates easier backporting of critical changes/fixes to legacy versions, which can prove handy for this project.

Either way, it would greatly help developers who would like to make their systems compliant with the new regulations by using this library, if both versioning and branching/release policies were established and clearly communicated.

Any thoughts/updates on that?

**Comment by lanusau** [comment]
+1 for Semantic versioning and release branches. Also, tag for each published release.

**Comment by lanusau** [comment]
Done
